"use client";
import { useEffect, useState } from "react";
import AuthGate from "@/components/AuthGate";
import NavBar from "@/components/NavBar";
import { auth } from "@/lib/firebase";
function PapersAdmin() {
 const [rows,setRows]=useState([]), [requests,setRequests]=useState([]), [form,setForm]=useState({id:"",className:"Paper Class",date:"",paperUrl:"",videoUrl:""}), [message,setMessage]=useState("");
 async function load(){const token=await auth.currentUser.getIdToken();const headers={Authorization:`Bearer ${token}`};const r=await fetch("/api/admin/papers",{headers});const d=await r.json();if(r.ok)setRows(d.lessons||[]);else setMessage(d.error||"Load failed");const q=await fetch("/api/admin/papers/requests",{headers});const qd=await q.json();if(q.ok)setRequests(qd.requests||[]);}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function review(id,status){const token=await auth.currentUser.getIdToken();const r=await fetch("/api/admin/papers/requests",{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({id,status})});const d=await r.json();if(!r.ok){setMessage(d.error||"Review failed");return;}load();}
 async function save(e){e.preventDefault();setMessage("");const token=await auth.currentUser.getIdToken();const {id,...data}=form;const r=await fetch("/api/admin/papers",{method:id?"PATCH":"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(id?{id,...data}:data)});const d=await r.json();if(!r.ok){setMessage(d.error||"Save failed");return;}setForm({id:"",className:"Paper Class",date:"",paperUrl:"",videoUrl:""});setMessage("Saved successfully");load();}
 return <><NavBar admin/><main className="container"><h1>Paper Class / Theory Lessons</h1><section className="card"><h2>Join Requests ({requests.length})</h2>{requests.map(q=><div key={q.id} style={{padding:"12px 0",borderBottom:"1px solid #ddd"}}><b>{q.fullName}</b> — {q.email}<p>{q.className}</p><button className="btn btn-success" onClick={()=>review(q.id,"approved")}>Approve</button> <button className="btn btn-danger" onClick={()=>review(q.id,"rejected")}>Reject</button></div>)}{!requests.length&&<p className="muted">No pending requests.</p>}</section><section className="card"><h2>{form.id?"Edit lesson":"Add lesson"}</h2><form onSubmit={save} className="grid"><label>Class<select value={form.className} onChange={e=>setForm({...form,className:e.target.value})}><option>Paper Class</option><option>Theory</option></select></label><label>Date<input type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Paper PDF / Drive link<input type="url" required placeholder="https://drive.google.com/..." value={form.paperUrl} onChange={e=>setForm({...form,paperUrl:e.target.value})}/></label><label>Video YouTube link (optional)<input type="url" placeholder="https://youtube.com/..." value={form.videoUrl} onChange={e=>setForm({...form,videoUrl:e.target.value})}/></label><button className="btn btn-primary">{form.id?"Update":"Add lesson"}</button>{message&&<p>{message}</p>}</form></section><h2>Lessons</h2><div className="grid">{rows.map(x=><section className="card" key={x.id}><b>{x.className} — {x.date}</b><p><a href={x.paperUrl} target="_blank" rel="noreferrer">Paper PDF</a></p>{x.videoUrl?<p><a href={x.videoUrl} target="_blank" rel="noreferrer">Watch video</a></p>:<p className="muted">Video not added</p>}<button className="btn" onClick={()=>setForm({id:x.id,className:x.className,date:x.date,paperUrl:x.paperUrl,videoUrl:x.videoUrl||""})}>Edit</button></section>)}</div></main></>;
}
export default function Page(){return <AuthGate role="admin">{()=> <PapersAdmin/>}</AuthGate>}
